# Application
spring.application.name=trip-service
server.port=8080

# Database - Supabase PostgreSQL
spring.datasource.url=jdbc:postgresql://db.bbfnkmzqftuvwesnmjkj.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=kiruthiyan1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# DevTools
spring.devtools.restart.enabled=true