package com.vfms.dsm.service;

import com.vfms.dsm.dto.*;
import com.vfms.dsm.entity.Driver;
import com.vfms.dsm.entity.DriverAvailability;
import com.vfms.dsm.mapper.DriverMapper;
import com.vfms.dsm.repository.DriverAvailabilityRepository;
import com.vfms.dsm.repository.DriverRepository;
import com.vfms.dsm.exception.DuplicateResourceException;
import com.vfms.dsm.exception.ResourceNotFoundException;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.UUID;
import java.time.LocalDate;
import java.util.List;
import com.vfms.user.entity.User;
import com.vfms.user.repository.UserRepository;

@Service
@RequiredArgsConstructor
@Transactional
public class DriverService {
    private static final String DRIVER_EMPLOYEE_ID_PREFIX = "DRV-";
    private static final int FIRST_DRIVER_EMPLOYEE_ID_NUMBER = 1001;
    private static final int MAX_EMPLOYEE_ID_ATTEMPTS = 100;

    private final DriverRepository driverRepository;
    private final DriverAvailabilityRepository availabilityRepository;
    private final DriverMapper driverMapper;
    private final UserRepository userRepository;

    public DriverResponse createDriver(DriverRequest request) {
        // Employee IDs are generated by the system so users cannot accidentally reuse one.
        request.setEmployeeId(generateUniqueEmployeeId());
        if (driverRepository.existsByNic(request.getNic()))
            throw new DuplicateResourceException("NIC already exists");
        Driver driver = driverMapper.toEntity(request);
        if (driver == null) {
            throw new IllegalArgumentException("Failed to map driver request to entity");
        }
        return toResponseWithAvailability(driverRepository.save(driver));
    }

    @Transactional(readOnly = true)
    public DriverResponse getDriver(UUID id) {
        return toResponseWithAvailability(findById(id));
    }

    @Transactional(readOnly = true)
    public Page<DriverResponse> getAllDrivers(Pageable pageable) {
        if (pageable == null) {
            throw new IllegalArgumentException("Pageable cannot be null");
        }
        // Fall back to newest-first ordering when the client does not supply an explicit sort.
        Pageable sortedPageable = PageRequest.of(
                pageable.getPageNumber(),
                pageable.getPageSize(),
                pageable.getSort().isSorted() ? pageable.getSort() : Sort.by(Sort.Direction.DESC, "createdAt")
        );
        return driverRepository.findAll(sortedPageable).map(this::toResponseWithAvailability);
    }

    public DriverResponse updateDriver(UUID id, DriverRequest request) {
        Driver driver = findById(id);
        // Apply incoming fields onto the managed entity, then persist the merged state.
        driverMapper.updateEntity(driver, request);
        if (driver == null) {
            throw new IllegalArgumentException("Failed to update driver entity");
        }
        return toResponseWithAvailability(driverRepository.save(driver));
    }

    public void deactivateDriver(UUID id) {
        Driver driver = findById(id);
        // Deactivation is modeled as a status change instead of deleting historical records.
        driver.setStatus(Driver.DriverStatus.INACTIVE);
        driverRepository.save(driver);
    }

    public void updateStatus(UUID id, Driver.DriverStatus status) {
        Driver driver = findById(id);
        // This endpoint lets the UI switch a driver between allowed workflow states.
        driver.setStatus(status);
        driverRepository.save(driver);
    }

    public Driver findById(UUID id) {
        if (id == null) {
            throw new IllegalArgumentException("Driver id cannot be null");
        }
        return driverRepository.findById(id)
            .orElseThrow(() -> new ResourceNotFoundException("Driver not found with id: " + id));
    }

    private DriverResponse toResponseWithAvailability(Driver driver) {
        DriverResponse response = driverMapper.toResponse(driver);
        DriverAvailability.AvailabilityStatus availabilityStatus = availabilityRepository.findById(driver.getId())
                .map(DriverAvailability::getStatus)
                .orElse(DriverAvailability.AvailabilityStatus.AVAILABLE);
        response.setAvailabilityStatus(availabilityStatus);
        return response;
    }

    private String generateUniqueEmployeeId() {
        // Fetch all DRV-prefixed IDs and find the highest sequential one in Java.
        // This avoids native SQL and correctly skips legacy 6-digit random IDs.
        int maxExisting = driverRepository.findAllEmployeeIdsByPrefix(DRIVER_EMPLOYEE_ID_PREFIX)
                .stream()
                .map(this::parseSequentialEmployeeIdNumber)
                .filter(n -> n >= FIRST_DRIVER_EMPLOYEE_ID_NUMBER && n <= 9999)
                .max(Integer::compareTo)
                .orElse(FIRST_DRIVER_EMPLOYEE_ID_NUMBER - 1);

        int nextNumber = maxExisting + 1;
        if (nextNumber < FIRST_DRIVER_EMPLOYEE_ID_NUMBER) {
            nextNumber = FIRST_DRIVER_EMPLOYEE_ID_NUMBER;
        }

        for (int attempt = 0; attempt < MAX_EMPLOYEE_ID_ATTEMPTS; attempt++, nextNumber++) {
            String employeeId = DRIVER_EMPLOYEE_ID_PREFIX + nextNumber;
            if (!driverRepository.existsByEmployeeId(employeeId)) {
                return employeeId;
            }
        }

        throw new DuplicateResourceException("Unable to generate a unique employee ID. Please try again.");
    }

    /** Parses the numeric suffix from a DRV-XXXX ID. Returns -1 if the format is invalid. */
    private int parseSequentialEmployeeIdNumber(String employeeId) {
        if (employeeId == null || !employeeId.startsWith(DRIVER_EMPLOYEE_ID_PREFIX)) return -1;
        try {
            return Integer.parseInt(employeeId.substring(DRIVER_EMPLOYEE_ID_PREFIX.length()));
        } catch (NumberFormatException ignored) {
            return -1;
        }
    }

    public Page<DriverUserResponse> getDriverUsers(Pageable pageable) {
        Page<User> users = userRepository.findByRoleAndDeletedAtIsNull(com.vfms.common.enums.Role.DRIVER, pageable);
        
        // Backfill missing driver IDs on the fly
        boolean savedAny = false;
        for (User user : users) {
            if (user.getEmployeeId() == null) {
                user.setEmployeeId(generateNextDriverId());
                userRepository.save(user);
                savedAny = true;
            }
            // Also ensure associated Driver record is present and synchronized
            syncDriverRecord(user);
        }
        if (savedAny) {
            userRepository.flush();
        }

        return users.map(this::toDriverUserResponse);
    }

    public DriverUserResponse getDriverUserById(UUID userId) {
        User user = userRepository.findById(userId)
                .filter(u -> u.getRole() == com.vfms.common.enums.Role.DRIVER && u.getDeletedAt() == null)
                .orElseThrow(() -> new ResourceNotFoundException("Driver user not found with id: " + userId));

        if (user.getEmployeeId() == null) {
            user.setEmployeeId(generateNextDriverId());
            userRepository.saveAndFlush(user);
        }
        syncDriverRecord(user);

        return toDriverUserResponse(user);
    }

    private void syncDriverRecord(User user) {
        Driver driver = null;
        if (user.getEmployeeId() != null) {
            driver = driverRepository.findByEmployeeId(user.getEmployeeId()).orElse(null);
        }
        if (driver == null && user.getEmail() != null && !user.getEmail().isBlank()) {
            driver = driverRepository.findByEmail(user.getEmail()).orElse(null);
        }
        if (driver == null && user.getNic() != null && !user.getNic().isBlank()) {
            driver = driverRepository.findByNic(user.getNic()).orElse(null);
        }
        if (driver == null) {
            driver = Driver.builder().employeeId(user.getEmployeeId()).build();
        }

        // Set employeeId on the driver if it is null or doesn't match
        if (driver.getEmployeeId() == null || !driver.getEmployeeId().equals(user.getEmployeeId())) {
            driver.setEmployeeId(user.getEmployeeId());
        }

        String fullName = user.getFullName() != null ? user.getFullName().trim() : "Driver";
        String firstName = fullName;
        String lastName = "";
        int lastSpaceIdx = fullName.lastIndexOf(' ');
        if (lastSpaceIdx > 0) {
            firstName = fullName.substring(0, lastSpaceIdx);
            lastName = fullName.substring(lastSpaceIdx + 1);
        }

        driver.setFirstName(firstName);
        driver.setLastName(lastName);
        driver.setFullName(fullName);
        driver.setNic(user.getNic() != null && !user.getNic().isBlank() ? user.getNic() : "TEMP-NIC-" + user.getId());
        driver.setEmail(user.getEmail());
        driver.setPhone(user.getPhone() != null ? user.getPhone() : "PENDING");
        driver.setLicenseNumber(user.getLicenseNumber() != null ? user.getLicenseNumber() : "PENDING");
        driver.setLicenseExpiryDate(user.getLicenseExpiryDate() != null ? user.getLicenseExpiryDate() : LocalDate.now().plusYears(1));
        driver.setStatus(user.getStatus() == com.vfms.common.enums.UserStatus.APPROVED && user.getDeletedAt() == null ? Driver.DriverStatus.ACTIVE : Driver.DriverStatus.INACTIVE);
        driverRepository.save(driver);
    }

    private String generateNextDriverId() {
        String prefix = "DRV-";
        List<String> userIds = userRepository.findAllEmployeeIdsByPrefix(prefix);
        List<String> driverIds = driverRepository.findAllEmployeeIdsByPrefix(prefix);

        int maxNumber = 1000; // start from 1001
        for (String id : userIds) {
            if (id != null && id.length() > prefix.length()) {
                try {
                    int number = Integer.parseInt(id.substring(prefix.length()));
                    if (number > maxNumber) {
                        maxNumber = number;
                    }
                } catch (NumberFormatException ignored) {}
            }
        }
        for (String id : driverIds) {
            if (id != null && id.length() > prefix.length()) {
                try {
                    int number = Integer.parseInt(id.substring(prefix.length()));
                    if (number > maxNumber) {
                        maxNumber = number;
                    }
                } catch (NumberFormatException ignored) {}
            }
        }

        return prefix + (maxNumber + 1);
    }

    private DriverUserResponse toDriverUserResponse(User user) {
        UUID linkedDriverId = driverRepository.findByEmail(user.getEmail())
                .map(Driver::getId)
                .orElse(null);

        return DriverUserResponse.builder()
                .id(user.getId())
                .fullName(user.getFullName())
                .email(user.getEmail())
                .phone(user.getPhone())
                .nic(user.getNic())
                .licenseNumber(user.getLicenseNumber())
                .licenseExpiryDate(user.getLicenseExpiryDate())
                .certifications(user.getCertifications())
                .experienceYears(user.getExperienceYears())
                .status(user.getStatus())
                .createdAt(user.getCreatedAt())
                .updatedAt(user.getUpdatedAt())
                .employeeId(user.getEmployeeId())
                .driverId(linkedDriverId)
                .build();
    }
}
