export const queryKeys = {
  adminDashboard: ["admin-dashboard"] as const,
  adminUsers: ["admin-users"] as const,
  adminDeletedUsers: ["admin-users", "deleted"] as const,
  adminUserCounts: ["admin-users", "counts"] as const,
  employeeRegistry: ["employee-registry"] as const,
  vehicles: (status: string) => ["vehicles", status] as const,
  vehicle: (id: string | number) => ["vehicle", String(id)] as const,
  rentals: (status: string) => ["rentals", status] as const,
  rental: (id: string | number) => ["rental", String(id)] as const,
  maintenance: (status: string) => ["maintenance", status] as const,
  maintenanceRequest: (id: string | number) =>
    ["maintenance-request", String(id)] as const,
  vendors: ["vendors"] as const,
  vendor: (id: string | number) => ["vendor", String(id)] as const,
  drivers: ["drivers"] as const,
  driver: (id: string | number) => ["driver", String(id)] as const,
  driverProfile: ["driver-profile"] as const,
  driverCertifications: ["driver-certifications"] as const,
  driverDocuments: ["driver-documents"] as const,
  driverLicenses: ["driver-licenses"] as const,
  driverLeaves: ["driver-leaves"] as const,
  driverInfractions: ["driver-infractions"] as const,
  trips: (role: string, userId: string) => ["trips", role, userId] as const,
  trip: (id: string | number) => ["trip", String(id)] as const,
  tripCalendar: (year: number, month: number) =>
    ["trip-calendar", year, month] as const,
  fuelRecords: ["fuel-records"] as const,
  fuelRecord: (id: string | number) => ["fuel-record", String(id)] as const,
  flaggedFuelRecords: ["fuel-records", "flagged"] as const,
  fuelMetadata: ["fuel-metadata"] as const,
};
